spring:
  application:
    name: demo
  datasource:
    url: "jdbc:sqlserver://localhost:1433;databaseName=dacn;encrypt=true;trustServerCertificate=true;"
    username: sa
    password: 123
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

